// CellWatcher.Setup.Helper — runs as the final step of the Burn bundle, after MariaDB and the
// CellWatcher.Setup.Msi package are both already installed. Does everything that needs real
// runtime logic rather than static installer authoring: creates the app's database/user/schema,
// probes the local network for Home Assistant, finalizes appsettings.json with what it found,
// and starts the service (or fires the scheduled task) so the app comes up already configured.

using System.Net.NetworkInformation;
using System.Net.Sockets;
using System.ServiceProcess;
using System.Text.Json;
using System.Text.Json.Nodes;
using MySqlConnector;

var options = ParseArgs(args);

Log($"CellWatcher.Setup.Helper starting. InstallDir={options.InstallDir}, InstallMode={options.InstallMode}");

await SetUpDatabaseAsync(options);
var haHost = await DetectHomeAssistantAsync();
FinalizeAppSettings(options, haHost);
StartApp(options);

Log("Done.");
return 0;

static HelperOptions ParseArgs(string[] args)
{
    string? installDir = null, mariaRootPassword = null, appDbPassword = null, installMode = "Service";
    var mariaPort = 3306;

    for (var i = 0; i < args.Length - 1; i++)
    {
        switch (args[i])
        {
            case "--install-dir": installDir = args[++i]; break;
            case "--maria-root-password": mariaRootPassword = args[++i]; break;
            case "--maria-port": mariaPort = int.Parse(args[++i]); break;
            case "--app-db-password": appDbPassword = args[++i]; break;
            case "--install-mode": installMode = args[++i]; break;
        }
    }

    if (installDir is null || mariaRootPassword is null || appDbPassword is null)
        throw new ArgumentException("Required: --install-dir, --maria-root-password, --app-db-password");

    return new HelperOptions(installDir, mariaRootPassword, appDbPassword, mariaPort, installMode ?? "Service");
}

static async Task SetUpDatabaseAsync(HelperOptions options)
{
    Log("Setting up MariaDB database, user, and schema...");

    var rootConnStr = $"Server=localhost;Port={options.MariaPort};User ID=root;Password={options.MariaRootPassword};";
    await using var conn = new MySqlConnection(rootConnStr);
    await conn.OpenAsync();

    await ExecuteAsync(conn, "CREATE DATABASE IF NOT EXISTS cellwatcher CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;");

    // MySqlConnector doesn't parameterize identifiers/DDL — appDbPassword is generated by the
    // Bundle (a random GUID-derived string, never user input), so this is not an injection risk.
    await ExecuteAsync(conn, $"CREATE USER IF NOT EXISTS 'CellWatcher'@'localhost' IDENTIFIED BY '{EscapeSqlString(options.AppDbPassword)}';");
    await ExecuteAsync(conn, "GRANT ALL PRIVILEGES ON cellwatcher.* TO 'CellWatcher'@'localhost';");
    await ExecuteAsync(conn, "FLUSH PRIVILEGES;");

    await conn.ChangeDatabaseAsync("cellwatcher");

    // Dependency order matters: cell_reading has a foreign key to cell_snapshot, and the alter_
    // scripts assume their target table already exists.
    string[] migrationOrder =
    [
        "create_battery_pack_reading.sql",
        "create_battery_cell_snapshot.sql",
        "create_battery_cell_reading.sql",
        "create_battery_cell_health.sql",
        "create_battery_health_metric.sql",
        "create_battery_ai_analysis.sql",
        "create_battery_ai_schedule.sql",
        "create_application_error.sql",
        "alter_battery_ai_analysis_add_cost.sql",
        "alter_battery_ai_analysis_add_status_level.sql",
        "alter_battery_ai_analysis_add_prompts.sql",
        "alter_battery_ai_schedule_multi_row.sql",
        "alter_battery_ai_schedule_engine_matrix.sql",
    ];

    var sqlDir = Path.Combine(AppContext.BaseDirectory, "sql");
    foreach (var fileName in migrationOrder)
    {
        var path = Path.Combine(sqlDir, fileName);
        if (!File.Exists(path)) { Log($"  (skipping {fileName} — not found)"); continue; }

        var sql = await File.ReadAllTextAsync(path);
        // ALTER ... ADD COLUMN on a column that already exists throws — harmless on a fresh
        // install (nothing pre-exists) but this same Helper binary could plausibly run again
        // during a repair, so tolerate "already there" rather than aborting the whole sequence.
        try { await ExecuteAsync(conn, sql); Log($"  Applied {fileName}"); }
        catch (MySqlException ex) when (ex.ErrorCode is MySqlErrorCode.DuplicateFieldName or MySqlErrorCode.DuplicateKeyEntry)
        {
            Log($"  Skipped {fileName} (already applied: {ex.Message})");
        }
    }
}

static async Task ExecuteAsync(MySqlConnection conn, string sql)
{
    await using var cmd = conn.CreateCommand();
    cmd.CommandText = sql;
    cmd.CommandTimeout = 60;
    await cmd.ExecuteNonQueryAsync();
}

static string EscapeSqlString(string value) => value.Replace("'", "''");

// Home Assistant's web UI listens on 8123 by default — a much more reliable signal than trying
// to fingerprint its MQTT traffic (which may not even be running yet, or use a broker HA doesn't
// host itself). A bounded-concurrency TCP sweep of the local /24, same shape as the app's own
// MqttDiscoveryService, but simpler since we're only checking one well-known port.
static async Task<string?> DetectHomeAssistantAsync()
{
    Log("Scanning the local network for Home Assistant (port 8123)...");

    var localIps = NetworkInterface.GetAllNetworkInterfaces()
        .Where(nic => nic.OperationalStatus == OperationalStatus.Up && nic.NetworkInterfaceType != NetworkInterfaceType.Loopback)
        .SelectMany(nic => nic.GetIPProperties().UnicastAddresses)
        .Where(ua => ua.Address.AddressFamily == AddressFamily.InterNetwork)
        .Select(ua => ua.Address.ToString())
        .ToList();

    if (localIps.Count == 0) { Log("  No local IPv4 network found — skipping."); return null; }

    var self = localIps.ToHashSet();
    var prefixes = localIps.Select(ip => ip[..ip.LastIndexOf('.')]).Distinct();
    var candidates = prefixes.SelectMany(prefix => Enumerable.Range(1, 254).Select(i => $"{prefix}.{i}"))
        .Where(h => !self.Contains(h))
        .ToList();

    using var gate = new SemaphoreSlim(50);
    string? found = null;

    var tasks = candidates.Select(async host =>
    {
        await gate.WaitAsync();
        try
        {
            using var client = new TcpClient();
            var connectTask = client.ConnectAsync(host, 8123);
            var winner = await Task.WhenAny(connectTask, Task.Delay(400));
            if (winner == connectTask && client.Connected)
                found ??= host;
        }
        catch { /* unreachable/refused — expected for almost all addresses scanned */ }
        finally { gate.Release(); }
    });

    await Task.WhenAll(tasks);

    Log(found is not null ? $"  Found Home Assistant at {found}:8123" : "  No Home Assistant instance found on the local network.");
    return found;
}

static void FinalizeAppSettings(HelperOptions options, string? haHost)
{
    Log("Finalizing appsettings.json...");

    var path = Path.Combine(options.InstallDir, "appsettings.json");
    var json = JsonNode.Parse(File.ReadAllText(path))!.AsObject();

    json["MariaDb"] ??= new JsonObject();
    json["MariaDb"]!["ConnectionString"] =
        $"Server=localhost;Port={options.MariaPort};Database=cellwatcher;User ID=CellWatcher;Password={options.AppDbPassword};";

    json["Mqtt"] ??= new JsonObject();
    if (haHost is not null)
    {
        // Home Assistant found: assume its Mosquitto add-on (if any) is reachable at the same
        // host on the standard MQTT port, and run as a client connecting out to it — matching
        // how this app's own MQTT client mode already works.
        json["Mqtt"]!["Mode"] = "Client";
        json["Mqtt"]!["Broker"] = haHost;
        json["Mqtt"]!["Port"] = 1883;
    }
    else
    {
        // No Home Assistant found: host our own broker locally so the emulator has *something*
        // to connect to regardless — the firewall rule for this is already in place from the MSI.
        json["Mqtt"]!["Mode"] = "Standalone";
    }

    File.WriteAllText(path, json.ToJsonString(new JsonSerializerOptions { WriteIndented = true }));
}

static void StartApp(HelperOptions options)
{
    if (options.InstallMode == "Service")
    {
        Log("Starting the CellWatcher service...");
        using var sc = new ServiceController("CellWatcher");
        try
        {
            if (sc.Status != ServiceControllerStatus.Running)
                sc.Start();
        }
        catch (Exception ex)
        {
            Log($"  Could not start the service automatically ({ex.Message}) — it's set to auto-start and will come up on next boot regardless.");
        }
    }
    else
    {
        Log("Running the CellWatcher scheduled task now...");
        try
        {
            System.Diagnostics.Process.Start("schtasks.exe", "/run /tn CellWatcher").WaitForExit(10_000);
        }
        catch (Exception ex)
        {
            Log($"  Could not run the scheduled task automatically ({ex.Message}) — it's set to run at startup and will come up on next boot regardless.");
        }
    }
}

static void Log(string message) => Console.WriteLine($"[CellWatcher.Setup.Helper] {message}");

sealed record HelperOptions(string InstallDir, string MariaRootPassword, string AppDbPassword, int MariaPort, string InstallMode);
